Repository bg0820/Assignment_Submission_System-Client, pull requests merged in 2020-04, with the labels that each got.

#15 Feature/register
  package.json
  src/App.jsx
  src/Components/Input/index.jsx
  src/Components/Input/style.scss
  src/Pages/Login/index.jsx
  src/Pages/Login/login.scss
  src/Pages/Register/index.jsx
  src/Pages/Register/style.scss
Labels: Component

#16 Feature/lecture
  src/App.jsx
  src/Components/Language/index.jsx
  src/Components/Language/style.scss
  src/Components/Table/index.jsx
  src/Components/Table/style.scss
  src/Pages/Lecture/index.jsx
  src/Pages/Lecture/style.scss
Labels: Documentation

#19 Feature/assignment pro
  src/App.jsx
  src/Components/FloatingMenu/index.jsx
  src/Components/FloatingMenu/style.scss
  src/Pages/AssignmentListPro/index.jsx
  src/Pages/AssignmentListPro/style.scss
Labels: Documentation

#20 Feature/lecture student
  src/App.jsx
  src/Pages/LectureStudent/index.jsx
  src/Pages/LectureStudent/style.scss
Labels: Documentation

#21 Feature/assignment list
  src/App.jsx
  src/Pages/AssignmentList/index.jsx
  src/Pages/AssignmentList/style.scss
Labels: Documentation

#22 Feature/editor
  src/App.jsx
  src/Pages/Editor/index.jsx
  src/Pages/Editor/style.scss
  src/Templates/CodeViewerLayout/index.jsx
  src/Templates/CodeViewerLayout/style.scss
  src/Templates/MainLayout/style.scss
Labels: Documentation

#23 #5 회원가입 유효성 검사 구현
  src/Pages/Register/index.jsx
  src/Pages/Register/style.scss
Labels: New Feature

#28 Feature/assignment add
  src/App.jsx
  src/Components/Example/index.jsx
  src/Components/Example/style.scss
  src/Components/Textarea/index.jsx
  src/Components/Textarea/style.scss
  src/Pages/AssignmentAdd/index.jsx
  src/Pages/AssignmentAdd/style.scss
Labels: Documentation
